### PR TITLE
Testing public monkey patched my own versions of enumerables methods in Enumerables module.

### PR DESCRIPTION
**Pull request by SamroodAli**
Please review the test suite I have written for the monkey patched public methods in Enumerables.rb
I have used contexts wherever necessary.
There was no universal subject or let needed.

I have used DSL Rspec for testing with keywords:
describe: for describing the public method,
it: for testing a particular feature
context: describing a context the problem is tested on.

The public methods in enumerable modules are: my_each, my_each_with_index, my_map, my_select, my_all? , my_none?, my_any? , my_count. my_inject. There is a private method match not tested as it is private and regex, class and other parameters are tested in individual enumerables. I believe I have tested for all cases, let me know if there should be any additional requirements. Thank you for your time and consideration. Happy Coding!

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

Very nice progress so far. You have done well testing for all your methods. However, there are some changes that you need to make in order to get your project approved

- [ ] Kindly test also for negative scenarios. For example, you can use similar tests
      

      let(:arr) { [1, -2, 3, 4] }
      
      it 'should not include negative numbers' do
        arr2 = arr.my_select(&:positive?)
        expect(arr2).not_to include(-2)
      end

      it 'should not return true if any elements in the block is not Integer' do
        expect([1, 2, 3, '4'].my_all? { |ele| ele.is_a?(Integer) }).not_to be true
      end

- [ ] Please use ```let``` instead of using variables inside the test cases [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/before_each.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

- [ ] Kindly fix this rubocop issues

a


<hr>

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 


> ps: . If you have any questions about my review or need help, you can message me on slack ( @Mkrtich Sargsyan )

**Comment by SamroodAli** [comment]
Thank you for the code review. 

- [ ] I have used let variables. There are five now at the top

I am using describe for class Enumerable which includes all the tests and happens to be more than 250 lines. I also can use more encompassing let this way.

- [ ] I have included negatives such as not include and not be true

- [ ] The last issue was concerning the `rubocop` offences. 

The issues were for max lines for blocks but 'describe' blocks are ignored regarding this issue.
In the `Microvoerse` file for `linters`, the `rubocop` has the rule to ignore `describe` blocks
you can check the rule here
[Microverse Linters for rubocop](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml)

Please update your rubocop config file and run the rspec again.
I hope I have addressed all issues, If not , do let me know @SamroodAli 
Thank you for your time and consideration.

Please review my PR again.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️
## Hi @SamroodAli

Good job on implementing the changes as requested in the previous review. You have done lots of testing. Well done.

I am mentioning one thing please include that in your readme before merging.

- [x] Please include your readme how to run the test. For now, I run `rspec` to run the test after entering it into your project folder.

**Do the change and merge**

**Keep being awesome devs and good luck with your next project!**
---------

Cheers and Happy coding!👏👏👏

Code review by **Dipesh Kumar**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional question).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

**Comment by SamroodAli** [comment]
Thank you @Dipeshtwis for the code review. I have included instructions in the readme. Thank you for letting me know. Happy Coding!

**Pull request merged**
